🧑‍⚕️Add wordpress for BMES.
acm-uic/IaC pull request #112
Opened 2024-10-17 20:33 UTC by SohamG

Haven't applied yet

2024-10-17 22:05 UTC, clee231 requested changes

2024-10-17 22:05 UTC, clee231 commented on kubernetes/argocd/stacks/bmes-wordpress/main.yml
> +            - WORDPRESS_DB_PASSWORD: notASecret
No credentials in this codebase, please! :pray:

2024-10-17 22:05 UTC, clee231 commented on kubernetes/argocd/stacks/bmes-wordpress/main.yml
> +          namespace: bmes
Did you mean `bmes-wordpress`?

2024-10-17 22:05 UTC, clee231 commented on kubernetes/argocd/stacks/bmes-wordpress/main.yml
> +          name: bmes # Perhaps move to new file.
On line 97 above, you name the service `wordpress`, not `bmes` as you define in this IngressRoute.

2024-10-18 20:24 UTC, SohamG commented on kubernetes/argocd/stacks/bmes-wordpress/certs.yml
> +    - convergehealth.cc
I fixed this

2024-10-18 20:25 UTC, SohamG commented on kubernetes/argocd/stacks/bmes-wordpress/main.yml
> +            - MYSQL_ROOT_PASSWORD: notASecret
the DB is not accessible from anywhere, its a multi container pod. Hence its not a secret

2024-10-18 20:27 UTC, SohamG commented
NOTES:
- I couldn't get the DB container to create the user/db/password etc on its own thru env variables. Tried Docker.io/mysql and then linuxserver/mariadb. I had to shell in to the container and make the users manually. I did make sure to delete the volumes when i changed init-only vars, but it just did not like them. maybe fix some day.

- TLS Resolves now

2024-10-19 02:30 UTC, SohamG commented on kubernetes/argocd/stacks/common/projects.yml
> +    description: Read-only privileges to sparkhacks
argh

2024-10-19 16:18 UTC, SohamG commented on kubernetes/argocd/stacks/common/projects.yml
> +    description: Read-only privileges to sparkhacks
fixed

2024-10-19 16:25 UTC, clee231 approved these changes

2024-10-19 16:28 UTC, merged